outing:
  app:
    reset-uri: http://localhost:4200/user/{userId}/reset-password/reset/{resetId}
server:
  port: '8080'
spring:
  application:
    name: auth-service
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/springsecurity?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ashishrefjob@gmail.com
    password: pwep kiwt leem cvzr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    prefer-ip-address: true
  application:
    name: auth-service
